baseurl = "http://www.ipmpoa.org.br/"
#baseurl = "http://example.org"
languageCode = "pt-br"
title = "Igreja Presbiteriana Metropolitana de Porto Alegre"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""
indexes = ""

[params]
	# General information
	#author = "IPM"
	#description = "Igreja Presbiteriana"
	#copyright = "Released under the MIT license"

	# Repository
	#provider = "GitHub"
	#repo_url = "https://github.com/digitalcraftsman/hugo-material-docs"

	#version = "1.0.0"
	logo = "images/logo/logo-ipm.png"
	favicon = "images/logo/logo-ipm-pequena.png"

	#permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "green"
    	accent  = "teal"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = ""
	github  = ""
	email   = ""



#[[menu.main]]
#	name   = "Quem Somos"
#	url    = "/"
#	weight = 10

[[menu.main]]
	name   = "Localização"
	url    = "localizacao/"
	weight = 11

[[menu.main]]
	name   = "Agenda"
	url    = "agenda/"
	weight = 12

[[menu.main]]
	name   = "Documentos Úteis"
	url    = "doc-uteis/"
	weight = 13

[[menu.main]]
	name   = "Liderança"
	url    = "lideranca/"
	weight = 14

[[menu.main]]
	name   = "Contato"
	url    = "contato/"
	weight = 15



[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
